added: detect(inference only) face, crop face using YOLOv8
pmz-q/est_wassup_03 pull request #29
Opened 2024-02-17 14:42 UTC by angie0bb

### 작업 내용
1. Detect with Yolov8 (inference only)
- 사전 학습된 weights를 가지고 face detection을 진행한다.
- 이때 얻은 bbox 정보(xywh, xyxy), 파일 명 (/emotion/filename.jpg 형식도 받아옴), original img array 는 따로 저장할 수 있음. 

2. Crop 옵션 ([colab](https://colab.research.google.com/drive/1OcoRqC1_boS62iNtJBbKCqnsZiog3asi#scrollTo=dirbfYG8zYW6) 참고)
(1) custom_padding: True (target size로 resizing)
    (i) yolo_padding = True: 얼굴 외의 영역을 가져와서 최대한 정사각형 shape을 만드는 crop
    (ii) yolo_padding = False: 얼굴 영역 만을 가져오고, 남는 여백은 black padding을 넣는 crop
(2) custom_padding = False: resize하지 않고 원본에서 얼굴 영역 그대로 crop (output 사이즈 다 제각기 다름)

*[Detect & Crop face를 하기 위한 데이터 사전 준비 과정]*
1. 원천 데이터에서 원하는 비율로 selected_images 를 복사해올 거면 sample_data_into_yolo_structure수행
4. create_feature_dataset을 이용해서 한글 파일 명 변경, coco json 생성 및, 원하는 est_wassup_03 폴더로 데이터 복사
5. (cropped 잘 되었는지 확인하는 단순 테스트용이라면) 그렇게 생성한 데이터셋 경로에서 detect_face.py 실행
6. (최종 cropped 셋을 원한다면) create_yolo_detection_dataset 먼저 실행 시키고, 거기서 나온 best weights를 /work/weights 폴더 안에 넣어둔다. 그 다음 3번 진행
-----------------------------------------------------------------------------
input dir 구조: yolo, output dir 구조: yolo
```
/data
  /test
      /anger
      /happy
  train
     /anger
     /happy
```

2024-02-17 16:00 UTC, pmz-q requested changes

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +  parser.add_argument("--target_size", type=tuple, default=(224,224)) # target cropping image size
_ 로 되어있는 부분들 - 로 통일시켜주세요.
 e.g. `--target_size` -> `--target-size`

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +  parser.add_argument("--custom_padding", type=bool, default=True) # if True: custom padding - PIL, add black pixels. if False: no padding, only crop (size will be different)
이건 개인적인 코딩 스타일이긴 한데, 
padding 들, argument 를 여러개를 받는 것 보단 choices 로 두는 건 어떨까요? 
e.g. `[custom, yolo, None]` 중 택 1 하도록.
[참고 링크](https://docs.python.org/3/library/argparse.html#choices)

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +  parser.add_argument("--target_size", type=tuple, default=(224,224)) # target cropping image size
그리고 이거 type=tuple 아마 못 받을거에요.. 아마도?
여러개 iterable 형태로 받고싶다면 아래의 링크들 참고해서 수정해보세요.
[링크 1](https://stackoverflow.com/questions/33564246/passing-a-tuple-as-command-line-argument)
[링크 2](https://docs.python.org/3/library/argparse.html#nargs)

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +    source_root = source_root + "/images"
만약에 source_root 가 필요한 이유가 `/images` 뿐이라면 아예 source_dir_path 를 `source_root/images` 로 받는것도 방법입니다.
그냥 코딩 취향이긴 한데요. 오류날 수 있는 경우가, 예를들어, 현재 저희 코드에서 그럴일은 없지만 혹여나 images 라는 폴더가 사라지는 경우가 있을 수 있기 때문에.. 취향입니다. 취존해주세요

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +    dirs = os.listdir(source_root)
[참고][지극히 개인적인 의견][수정 안 해도 됨]
사실 여기서 dirs 가 train, val, test 이 세개로 고정이기 때문에, listdir 을 활용하는 것 보단 아예 tuple 로 고정해버리는것도 좋습니다.
이것도 코딩 취향이긴 합니다만.. os 를 활용하는것이 사실은 에러 핸들링 하는것이 매우 귀찮기 때문에,
예를들어, 원치 않는 파일이 쓸데없이 들어가 있는 경우도 있을 수 있으니까요. 
경우의 수가 많다면 적기 귀찮으니 listdir 사용할 수 있겠으나 세개면 뭐.. 적는것도 괜찮다고 생각합니다.

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +                if save_bbox_dir is not None:
이건 어떤 용도로 저장하는 건가요?

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +    return all_pred_bbox_results
이거 리턴 값 받아서 아무것도 안 하고 있는 것 같은데요. 왜 만들고 왜 리턴하는건가요? 용도가 무엇이었나요?

2024-02-17 16:00 UTC, pmz-q commented on tools/detect_face.py
> +    return all_pred_bbox_results
설명해주셨는데 아무래도 제가 이해를 제대로 못한 것 같습니다.

2024-02-17 16:00 UTC, pmz-q commented on tools/crop_face.py
> +    if yolo_padding == True:  # yolo padding - expand facial areas
만약 custom_padding 은 False 고 yolo_padding 만 True 이라면 어떻게 되나요?

2024-02-18 07:29 UTC, angie0bb commented on tools/detect_face.py
> +    return all_pred_bbox_results
리턴만 하는 건 제가 처리를 안해줬던 부분이구요....ㅎ
원래 용도는 inference 만 한거 가지고 metrics 뽑아보기 위해서 bbox 정보 저장하는 용도였습니다. 
근데, 이제 필요 없긴합니다.
사실 혹시 cropped image가 손상되었을 때도 대비하는 용도로도 (다시 detect 안 돌리게) 쓰려했는데,,json 파일로 저장하려면 엄청 커지고 오래걸릴 것 같아요.

2024-02-18 07:30 UTC, angie0bb commented on tools/detect_face.py
> +                if save_bbox_dir is not None:
이건 오리지널 이미지에 bounding box 정보 그린 이미지를 저장하는 건데요. bbox 잘 그려졌는지 cropped image만 보고 판단하면 혹시 어려울까봐 넣어두었습니다.

2024-02-18 08:31 UTC, pmz-q commented on tools/detect_face.py
> +    return all_pred_bbox_results
네네, cropped data 손상되거나 다시 만들어야하면 그냥 model weight 같은거 써서 스크립트 다시 돌리는 것으로 하시죠~

2024-02-18 08:33 UTC, pmz-q commented on tools/detect_face.py
> +                if save_bbox_dir is not None:
아하, 그렇다면 혹시 이미지 전체 말고 일부민 (e.g. train/val/test 별 sample 20개) 저장하게끔 수정 가능할까요? 전체를 저장하면 용량이 너무 커질 것 같습니다

2024-02-18 08:34 UTC, pmz-q commented on tools/detect_face.py
> +    return all_pred_bbox_results
이 부분은 주석처리 해주시고 (bbox 저장하는 부분) 나중에 필요하겠다 싶을 때 코드 살리죠...!!

2024-02-18 10:09 UTC, angie0bb commented on tools/detect_face.py
> +    return all_pred_bbox_results
넵 주석처리할게요!

2024-02-18 10:10 UTC, angie0bb commented on tools/crop_face.py
> +    if yolo_padding == True:  # yolo padding - expand facial areas
ㅎㅎ..이거 options으로 주면서 custom, yolo, no_padding 세가지 elif로 처리하며 변경했습니다.

2024-02-18 10:10 UTC, angie0bb commented on tools/detect_face.py
> +    source_root = source_root + "/images"
오호 취존했습니다!

2024-02-18 10:14 UTC, angie0bb commented on tools/detect_face.py
> +    dirs = os.listdir(source_root)
그렇군요! os빼고 고정하는 걸로 처리했습니다.
이거 처리하면서 하나 arg parser추가했는데요.
images폴더 안에 train, val, test를 parser로 입력 받아서 원하는 폴더만 처리할 수 있게 수정했습니다.
이유는
1) 이미지 양이 많아지면 한 세월 걸릴 것 같아요. (장당 7.8ms) 그래서 터미널 여러개 열어서 폴더별로 병렬 처리할 수 있도록 만들었어요. 병렬로 처리해도 장당 처리속도는 똑같더라구요.
요 내용은 푸시 할때 다시 정리해서 코멘트 달아두겠습니다.

2024-02-18 10:23 UTC, angie0bb commented on tools/detect_face.py
> +                if save_bbox_dir is not None:
넵! 수정했습니다.

2024-02-18 11:36 UTC, pmz-q approved these changes
comment 부분들만 수정해주시고 머지 해주세요~~~

2024-02-18 11:36 UTC, pmz-q commented on tools/detect_face.py
> +  parser.add_argument("--dir-option", nargs="+", type=str, default=("train", "val", "test"), help="choose specific folders to detect&crop")
choices 로 바꾸는게 나을 것 같습니다.

2024-02-18 11:36 UTC, pmz-q commented on tools/detect_face.py
> +  parser.add_argument("--padding-option", type=str, default="custom", choices=["custom", "yolo", "no_padding"], help="custom: resizing and add black pixels, yolo: no black pad, expand facial area to
"no_padding" 보다는 default 를 None 으로 주는것은 어떨까요?

2024-02-18 11:36 UTC, pmz-q commented on tools/detect_face.py
> +  parser.add_argument("--weights-path", type=str, default="/home/KDT-admin/work/weights/yolov8n-face.pt", help="pretrained weights path to load")
weight 경로의 경우, est_wassup_03 폴더 내에 있으면 좋을 것 같습니다. 경로 어떻게 할 것인지 한번 고민해봐야겠네요. 같이 고민해봐주세요! 이 부분 수정은 나중에 하시죠~

2024-02-18 13:39 UTC, angie0bb commented
- 코멘트 추가된 부분 반영 완료
  - dir-option choices로 변경
  - padding-option None으로 변경
- [문서 작성 참고용] 추가한 부분 (이전 커밋)
  -  `argparse --dir-option' 에서 train, val, test 중 원하는 폴더를 1개 이상 선택할 수 있습니다. 새로운 터미널에서 폴더별로 병렬 처리하기 위함입니다.

2024-02-19 00:10 UTC, merged